services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:8080"
    expose:
      - "8080"
  
  nginx:
    image: nginx
    ports:
      - "8102:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
